name: hyperparam_example
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - numpy
    - click
    - pandas
    - scipy
    - scikit-learn
    - tensorflow
    - matplotlib
    - keras
    - mlflow
    - hyperopt
    - protobuf<4.0.0